FACEBOOK_KEY: "718038748338121"
FACEBOOK_SECRET: b1ac12447e68e164d689b3b951b6b696
TWITTER_KEY: BJQWkyUbLB2vAyFwOGEEzWqzJ
TWITTER_SECRET:   X6AsDCSTDmzG1GluWLIRy2UewQH9cTBHG4EWo9PB8bu19559EZ
GOOGLE_CLIENT_ID: 746727097020-rb5gp37bdeg8js6rle0j6tpiit43iu4v.apps.googleusercontent.com
GOOGLE_SECRET: lnK3QqPFGha7GSXMV9auv-ia